stages:
  - deploy
  - check


deployBeta:
  stage: deploy
  script:
    - curl "https://api.telegram.org/bot$TG_LUPINE_GUY/sendMessage?chat_id=$DEPLOY_LOG_CHANNEL&text=$CI_PROJECT_TITLE%3A $CI_JOB_NAME started⏳ %0A$CI_COMMIT_MESSAGE "
    - apt-get -y update
    - apt-get -y upgrade
    - apt-get install -y python3-pip
    - pip3 install docker-compose
    - docker image prune -f
    - echo "DISPATCHER_TOKEN=$BETA_TOKEN" > .env
    - echo "RANK_ADMINS=$RANK_ADMINS" >> .env
    - echo "EMOJI_ADMINS=$EMOJI_ADMINS" >> .env
    - echo "DEV_GROUP=$DEV_GROUP" >> .env
    - echo "DATABASE=$DATABASE" >> .env
    - echo "ADMINS=$ADMINS" >> .env
    - docker-compose -f docker-compose.yml build --no-cache
    - docker-compose -f docker-compose.yml up -d
    - curl "https://api.telegram.org/bot$TG_LUPINE_GUY/sendMessage?chat_id=$DEPLOY_LOG_CHANNEL&text=$CI_PROJECT_TITLE%3A $CI_JOB_NAME finished✅ %0A$CI_COMMIT_MESSAGE "
  only:
    - beta
  tags:
    - beta


deployMain:
  stage: deploy
  script:
    - curl "https://api.telegram.org/bot$TG_LUPINE_GUY/sendMessage?chat_id=$DEPLOY_LOG_CHANNEL&text=$CI_PROJECT_TITLE%3A $CI_JOB_NAME started⏳ %0A$CI_COMMIT_MESSAGE"
    - sudo apt-get install -y python3-pip
    - sudo pip3 install docker-compose
    - sudo docker image prune -f
    - echo "DISPATCHER_TOKEN=$MAIN_TOKEN" > .env
    - echo "RANK_ADMINS=$RANK_ADMINS" >> .env
    - echo "EMOJI_ADMINS=$EMOJI_ADMINS" >> .env
    - echo "DEV_GROUP=$DEV_GROUP" >> .env
    - echo "DATABASE=$DATABASE" >> .env
    - echo "ADMINS=$ADMINS" >> .env
    - sudo docker-compose -f docker-compose.yml build --no-cache
    - sudo docker-compose -f docker-compose.yml up -d
    - curl "https://api.telegram.org/bot$TG_LUPINE_GUY/sendMessage?chat_id=$DEPLOY_LOG_CHANNEL&text=$CI_PROJECT_TITLE%3A $CI_JOB_NAME finished✅ %0A$CI_COMMIT_MESSAGE"
  only:
    - master
  tags:
    - mainserver

on_deploy_failure:
    stage: check
    script:
    - curl "https://api.telegram.org/bot$TG_LUPINE_GUY/sendMessage?chat_id=$DEPLOY_LOG_CHANNEL&text=$CI_PROJECT_TITLE%3A deploy failed❌ %0A$CI_COMMIT_MESSAGE"
    when: on_failure

